version: '3'

services:
  app:
    container_name: app
    build: .
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - .:/app:delegated
      - ~/.composer:/home/root/.composer:delegated
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_database/mysql-data:/var/lib/mysql:rw
volumes:
  mysql-data:
